# This file has been generated by Niv.

let

  #
  # fetchTarball version that is compatible between all the versions of
  # Nix. Nix 1.2 through 2.3 have a slightly different fetchTarball that
  # doesn't accept the sha256 argument, so we need to use the attribute
  # form.
  #
  fetchTarball =
    { url, sha256 }:
    if builtins.lessThan builtins.nixVersion "1.12" then
      builtins.fetchTarball { inherit url; }
    else
      builtins.fetchTarball { inherit url sha256; };

  #
  # The fetchers. fetch_<type> fetches the source for a particular type
  # of fetcher, given the source definition.
  #
  fetch_tarball = name: spec:
    fetchTarball {
      inherit (spec) url sha256;
    };

  #
  # The sources. These are the actual sources that are used to build
  # the system.
  #
  sources = builtins.fromJSON (builtins.readFile ./sources.json);

  #
  # The sources as a set of fetchers.
  #
  sources_ = builtins.mapAttrs (name: spec:
    if builtins.hasAttr "type" spec then
      if spec.type == "tarball" then
        fetch_tarball name spec
      else
        abort "Unknown source type ${spec.type} for source ${name}"
    else
      abort "No type specified for source ${name}"
  ) sources;

in

{ inherit sources sources_; }
