- name: ollama_chat/qwen3:30b-a3b
  edit_format: diff
  use_repo_map: true
  extra_params:
    max_tokens: 40960
    top_p: 0.95
    temperature: 0.7
  editor_model_name: ollama_chat/qwen3:30b-a3b
  editor_edit_format: editor-diff
