export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\] $ \[\e]2;\u@\h:\w\a\]"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.config/opencode/dev/bin:$PATH"
mkdir -p "$HOME/.npm-global"


