{
  pkgs,
  lib,
  packageSets ? {
    pkgs = pkgs;
  },
  ensureInstalled ? [],
  nvimPackage ? pkgs.neovim,
  nvimConfigPath ? ./nvim,
  nvimProfileName ? "neonix",
  impureNpmPackage ? pkgs.nodejs,
  impureCargoPackage ? null,
  impureNugetPackage ? null,
  impureComposerPackage ? null,
  impureLuaRocksPackage ? null,
}: let
  roots = builtins.attrNames packageSets;

  builderPkgs =
    if roots == []
    then throw "packageSets must not be empty"
    else packageSets.${builtins.head roots};

  uniqueStrings = xs:
    builtins.attrNames (
      builtins.listToAttrs (map (x: {
          name = builtins.unsafeDiscardStringContext (toString x);
          value = true;
        })
        xs)
    );

  uniqueDerivations = drvs:
    builtins.attrValues (
      builtins.listToAttrs (map (drv: {
          name = builtins.unsafeDiscardStringContext (toString drv);
          value = drv;
        })
        drvs)
    );

  extractRefs = text: let
    parts = builtins.split ''[$][{]([^}]*)[}]'' text;

    allRefs = builtins.concatLists (
      map (
        x:
          if builtins.isList x
          then [(builtins.elemAt x 0)]
          else []
      )
      parts
    );

    isWantedRef = ref: let
      m = builtins.match "^([^.]+)\\..+$" ref;
    in
      m != null && builtins.hasAttr (builtins.elemAt m 0) packageSets;
  in
    builtins.filter isWantedRef allRefs;

  collectFiles = path: prefix: let
    entries = builtins.readDir path;
    names = builtins.attrNames entries;
  in
    builtins.concatLists (
      map
      (
        name: let
          kind = entries.${name};
          p = path + "/${name}";
          rel =
            if prefix == ""
            then name
            else "${prefix}/${name}";
        in
          if kind == "directory"
          then collectFiles p rel
          else if kind == "regular"
          then [
            {
              abs = p;
              inherit rel;
            }
          ]
          else []
      )
      names
    );

  files = collectFiles nvimConfigPath "";

  resolveRef = { ref, file ? null }: let
    m = builtins.match "^([^\\.]+)\\.(.+)$" ref;
    root = builtins.elemAt m 0;
    attrPath = builtins.split "\\." (builtins.elemAt m 1);
    pathStr = builtins.concatStringsSep "." attrPath;
    fileMsg =
      if file == null
      then ""
      else " in file ${file}";
  in
    lib.attrByPath attrPath
      (throw "Could not find attribute '${pathStr}' in packageSets.${root}${fileMsg}")
      packageSets.${root};

  fileRefs =
    map
    (f: {
      inherit (f) rel abs;
      refs = uniqueStrings (extractRefs (builtins.readFile f.abs));
    })
    files;

  refs = uniqueStrings (
    builtins.concatLists (map (f: f.refs) fileRefs)
  );

  foundPackages = uniqueDerivations (
    (builtins.concatLists (
      map (f: map (ref: resolveRef { inherit ref; file = f.rel; }) f.refs) fileRefs
    ))
    ++
    (map (ref: resolveRef { inherit ref; }) ensureInstalled)
  );

  replacementMap = builtins.listToAttrs (
    builtins.concatLists (
      map
      (f:
        map
        (ref: {
          name = "\${${ref}}";
          value = toString (resolveRef { inherit ref; file = f.rel; });
        })
        f.refs)
      fileRefs
    )
  );

  replaceFrom = builtins.attrNames replacementMap;
  replaceTo = map (k: replacementMap.${k}) replaceFrom;

  rewriteText = text:
    builtins.replaceStrings replaceFrom replaceTo text;

  rewrittenFiles =
    map
    (f: let
      content = rewriteText (builtins.readFile f.abs);
      src =
        builderPkgs.writeText
        "rewritten-${builtins.substring 0 16 (builtins.hashString "sha256" f.rel)}-${baseNameOf f.rel}"
        content;
    in {
      inherit (f) rel;
      inherit src;
    })
    files;

  shellEscape = s: "'${builtins.replaceStrings ["'"] ["'\\''"] s}'";

  installScript = builtins.concatStringsSep "\n" (
    map
    (f: ''
      mkdir -p "$out/$(dirname ${shellEscape f.rel})"
      cp ${f.src} "$out/${f.rel}"
    '')
    rewrittenFiles
  );

  nvimProfileState = builtins.concatStringsSep "" ["$HOME/.local/state/" nvimProfileName];
  initFileSetup = ''
    -- AUTOGENERATED BY NEONIX
    vim.g.lazyvim_json = "/etc/nixos/common/nvim/lazy-lock.json"
    -- END AUTOGENERATED BY NEONIX
  '';

  profileInstallPackages = map (drv: builtins.unsafeDiscardStringContext (toString drv)) foundPackages;

  envExports = ''
    ${
      if impureCargoPackage != null
      then ''
        export CARGO_HOME="${nvimProfileState}/cargo"
        export RUSTUP_HOME="${nvimProfileState}/rustup"
      ''
      else ""
    }

    ${
      if impureNpmPackage != null
      then ''
        export NPM_CONFIG_PREFIX="${nvimProfileState}/npm"
        export NODE_PATH="${nvimProfileState}/npm/lib/node_modules"
      ''
      else ""
    }

    ${
      if impureComposerPackage != null
      then ''
        export COMPOSER_HOME="${nvimProfileState}/composer"
      ''
      else ""
    }

    ${
      if impureNugetPackage != null
      then ''
        export NUGET_PACKAGES="${nvimProfileState}/nuget"
      ''
      else ""
    }

    export PATH="${nvimProfileState}/bin-wrapped:$HOME/.${nvimProfileName}/bin:$PATH"
  '';

  mkWrapper = {name}: ''
    #!/usr/bin/env bash
    ${envExports}
    exec ${name} "$@"
  '';

  activationScript = ''
    export NEONIX_PROFILE="$HOME/.${nvimProfileName}"
    export NEONIX_STATE="${nvimProfileState}"
    export NEONIX_STATE_WRAPPED="${nvimProfileState}/bin-wrapped"

    mkdir -p "$NEONIX_STATE_WRAPPED"
    rm -rf "$NEONIX_STATE_WRAPPED"/*

    mkdir -p \
      "$NEONIX_STATE/cargo" \
      "$NEONIX_STATE/rustup" \
      "$NEONIX_STATE/npm" \
      "$NEONIX_STATE/npm/lib/node_modules" \
      "$NEONIX_STATE/composer" \
      "$NEONIX_STATE/nuget"

    ${
      if impureNpmPackage != null
      then ''
        echo "${mkWrapper {name = "npm";}}" > "$NEONIX_STATE_WRAPPED/npm"
        chmod a+x "$NEONIX_STATE_WRAPPED/npm"
      ''
      else ""
    }

    ${
      if impureCargoPackage != null
      then ''
        echo "${mkWrapper {name = "cargo";}}" > "$NEONIX_STATE_WRAPPED/cargo"
        chmod a+x "$NEONIX_STATE_WRAPPED/cargo"
      ''
      else ""
    }

    ${
      if impureComposerPackage != null
      then ''
        echo "${mkWrapper {name = "composer";}}" > "$NEONIX_STATE_WRAPPED/composer"
        chmod a+x "$NEONIX_STATE_WRAPPED/composer"
      ''
      else ""
    }

    ${
      if impureNugetPackage != null
      then ''
        echo "${mkWrapper {name = "nuget";}}" > "$NEONIX_STATE_WRAPPED/nuget"
        chmod a+x "$NEONIX_STATE_WRAPPED/nuget"
      ''
      else ""
    }

    nix profile remove --all --profile "$NEONIX_PROFILE"
    ${builtins.concatStringsSep "\n" (map (pkg: ''
        nix profile add --profile "$NEONIX_PROFILE" ${shellEscape pkg}
      '')
      profileInstallPackages)}
  '';

  nvim-config = builderPkgs.runCommand "rewritten-nvim-config" {} ''
    mkdir -p "$out"
    ${installScript}

    chmod u+w "$out/init.lua"
    tmp="$(mktemp)"
    {
      printf '%s\n' '${initFileSetup}'
      cat "$out/init.lua"
    } > "$tmp"
    mv "$tmp" "$out/init.lua"
  '';

  wrappedNvimBin = pkgs.writeShellScriptBin "nvim" ''
    ${envExports}
    exec ${nvimPackage}/bin/nvim "$@"
  '';
in {
  nvim-wrapped = pkgs.symlinkJoin {
    name = "${nvimPackage.pname or "neovim"}-${nvimPackage.version or "wrapped"}";
    paths = [nvimPackage];
    postBuild = ''
      rm -f $out/bin/nvim
      mkdir -p $out/bin
      cp ${wrappedNvimBin}/bin/nvim $out/bin/nvim
      chmod +x $out/bin/nvim
    '';
    lua = nvimPackage.lua;
    meta = nvimPackage.meta;
    passthru = nvimPackage.passthru or {};
  };
  nvim-activation = activationScript;
  inherit nvim-config;
}
